#!/bin/bash
# build-canoe-kleaf.sh — jm2 OEM-Kleaf build driver for canoe (OnePlus SM8850).
#
# Invoked by the LineageOS <-> OEM-Kleaf adapter in vendor/lineage's kernel.mk
# (TARGET_KERNEL_PLATFORM_BUILD_WRAPPER). The adapter runs us with cwd = the OEM
# repo root (TARGET_KERNEL_PLATFORM_ROOT, e.g. .../kernel-6.12), then copies the
# kernel dist into KERNEL_OUT.
#
# Why a wrapper (vs calling oplus_build_kernel.sh directly): the OEM kernel build
# (build_with_bazel.py) only builds soc-repo targets generated by define_canoe, so
# it EXCLUDES every //vendor/... DDK module set: the QC techpacks (display msm_drm,
# graphics msm_kgsl, camera, video/eva, audio, datarmnet/dataipa, securemsm, BT,
# dsp/fastrpc, mm-drivers, mmrm, synx, NFC) plus WLAN (cnss2/qcacld — cnss2 carries
# the OnePlus 15 byte-reversed-WLAN-MAC WiFi fix) and the oplus vendor modules not
# already merged by prepare_vendor. Without these the ROM has no display/audio/WiFi.
# We build ALL canoe_perf vendor dist targets against the SAME kernel_build (so
# KMI/CRCs match), plus extract the GKI system_dlkm modules the kernel build
# already produced into its staging archive, and merge everything into the kernel
# dist. Goal: full stock-module-set parity, fully source-built.
# See kernel/oneplus/sm8850-modules/KLEAF_WIREUP_PLAN.md.
#
# Usage: build-canoe-kleaf.sh <platform> <variant>   (e.g. canoe perf)
set -uo pipefail

# Detach stdin: the OEM kernel build runs `make oldconfig`, which prompts for any
# NEW Kconfig symbols. With EOF on stdin it auto-takes the defaults (exactly what
# the OEM's own clean build does); without it, a non-interactive caller (brunch,
# background) would block forever waiting for input.
exec </dev/null

PLATFORM="${1:?platform arg required (e.g. canoe)}"
VARIANT="${2:?variant arg required (e.g. perf)}"
TV="${PLATFORM}_${VARIANT}"

# We are run with cwd = OEM repo root; resolve everything from here.
ROOT="$(pwd)"
KP="$ROOT/kernel_platform"
DIST="$KP/out/msm-kernel-${PLATFORM}-${VARIANT}/dist"
CACHE="$ROOT/bazel-cache"
BAZEL="$KP/tools/bazel"
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
MERGE_MANIFEST="$DIST/.jm2-vendor-merged.txt"

# Stock module-load lists (parity reference + coverage gate). Overridable for
# other devices consuming this wrapper.
STOCK_MODULES_DIR="${STOCK_MODULES_DIR:-/run/media/jmulesa/lineage/android/lineage/device/oneplus/infiniti-kernel/modules}"

# grep is wrapped to ugrep in some shells and breaks the OEM scripts' parsing
# (same failure mode as `lunch`); neutralize it here. (reference_grep_ugrep_breaks_lunch)
unalias -a 2>/dev/null || true
unset -f grep egrep fgrep 2>/dev/null || true

fail() { echo "[jm2-kleaf] ERROR: $*" >&2; exit 1; }

[ -d "$STOCK_MODULES_DIR" ] || fail "STOCK_MODULES_DIR not found: $STOCK_MODULES_DIR (external drive unmounted?)"

echo "[jm2-kleaf] === 1/4 OEM kernel build ($TV) ==="
# The OEM scripts pipe through tee with no pipefail (their exit code is
# meaningless) and a fully-cached rebuild rewrites NO dist files (so mtime
# freshness is also meaningless). Detect failure from bazel's own error
# sentence inside the LOGDIR log this run just wrote, then sanity-check the
# artifacts exist; the vermagic gate in step 4 catches content staleness.
STAMP="$(mktemp)" || fail "mktemp failed"
./kernel_platform/oplus/build/oplus_build_kernel.sh "$PLATFORM" "$VARIANT"
OEM_LOG="$(find "$ROOT/LOGDIR" -name 'build_*.log' -newer "$STAMP" 2>/dev/null | sort | tail -1)"
rm -f "$STAMP"
[ -n "$OEM_LOG" ] || fail "OEM build wrote no LOGDIR log — did oplus_build_kernel.sh run at all?"
if grep -qE 'Build did NOT complete successfully' "$OEM_LOG"; then
  fail "OEM kernel build FAILED (see $OEM_LOG)"
fi
for a in Image build_opts.txt system_dlkm_staging_archive.tar.gz system_dlkm.modules.load vendor_dlkm.modules.load; do
  [ -s "$DIST/$a" ] || fail "missing dist artifact after kernel build: $a"
done

# Reuse the EXACT bazel config the kernel build recorded, so the vendor DDK modules
# build against the same ${TV} base kernel_build (cache hit + matching vermagic/CRCs).
# build_opts.txt stores opts with %workspace% tokens; expand them to $KP.
[ -s "$DIST/build_opts.txt" ] || fail "build_opts.txt missing/empty — cannot pin vendor builds to the kernel's bazel config"
mapfile -t KOPTS < <(sed "s|%workspace%|$KP|g" "$DIST/build_opts.txt" | sort -u | grep -v '^$')
[ "${#KOPTS[@]}" -gt 0 ] || fail "no bazel opts parsed from build_opts.txt"

# Unpack the GKI system_dlkm staging archive once (used for the zram-collision
# resolution below and the GKI merge in step 3).
GKI_TMP="$(mktemp -d)" || fail "mktemp -d failed"
trap 'rm -rf "$GKI_TMP"' EXIT
tar -xzf "$DIST/system_dlkm_staging_archive.tar.gz" -C "$GKI_TMP" || fail "system_dlkm staging archive extract failed"

# Dual-copy collision resolution (stock ships zram.ko/zsmalloc.ko TWICE: GKI
# copies in system_dlkm and oplus-patched copies in vendor_dlkm; the flat dist
# can hold only one and the soc-repo build put the VENDOR copies there). Any
# system_dlkm.modules.load entry whose flat .ko differs from the GKI archive
# copy is a vendor-built collision: staging it into the GKI-only system_dlkm
# depmod set fails on the oplus symbols, and the recipe's comm split would
# subtract it from vendor_dlkm (silently losing e.g. zram). Drop such names
# from system_dlkm.modules.load — the vendor copy ships and loads via the
# stock vendor_dlkm list, which is what the OEM device actually uses.
collisions=0
tmp_load="$(mktemp)"
while read -r p; do
  [ -z "$p" ] && { continue; }
  n="$(basename "$p")"
  src="$(find "$GKI_TMP" -name "$n" -type f | head -1)"
  if [ -f "$DIST/$n" ] && [ -n "$src" ] && ! cmp -s "$DIST/$n" "$src"; then
    echo "[jm2-kleaf] system_dlkm/vendor name collision: $n is vendor-built in the flat dist — dropping from system_dlkm.modules.load (vendor copy ships via the vendor_dlkm list)"
    collisions=$((collisions+1))
  else
    echo "$p" >> "$tmp_load"
  fi
done < "$DIST/system_dlkm.modules.load"
[ "$collisions" -gt 0 ] && mv "$tmp_load" "$DIST/system_dlkm.modules.load" || rm -f "$tmp_load"
echo "[jm2-kleaf] system_dlkm collision pass: $collisions name(s) resolved to the vendor copy"

VSTAGE="$ROOT/vendor_modules_dist"
rm -rf "$VSTAGE"; mkdir -p "$VSTAGE"

echo "[jm2-kleaf] === 2/4 vendor DDK module set ($TV) against the $TV kernel ==="
# bazel must run from the workspace root (kernel_platform), not the repo root
cd "$KP" || fail "cannot cd to workspace $KP"

# Enumerate every canoe_perf vendor dist target (same registry build_with_bazel
# queries, but across //vendor/... which it skips). Filter out the per-target
# internal helpers and qcacld's per-chipset duplicates of all_modules_dist.
mapfile -t TARGETS < <("$BAZEL" --output_user_root="$CACHE" query --keep_going \
    "filter(\"${TV}.*dist\", //vendor/...)" 2>/dev/null \
  | grep -E '^//' \
  | grep -vE '_dist_dist_manifest$|_dist_dist_tool$|_dist_internal$' \
  | grep -vE "qcacld-3\.0:${TV}_(kiwi|peach|wcn).*_modules_dist$" \
  | sort -u)
[ "${#TARGETS[@]}" -gt 20 ] || fail "vendor dist target enumeration returned only ${#TARGETS[@]} targets (expected ~79) — query broken?"
echo "[jm2-kleaf] ${#TARGETS[@]} vendor dist targets enumerated"

# One parallel build of everything first (much faster than serial runs), tolerant
# of individual target failures; then run each dist target (cache-hot) to copy its
# modules into a PER-TARGET stage subdir (so same-basename outputs from different
# packages can be cross-checked instead of silently last-winning).
# copy_to_dist_dir runners take --dist_dir; pkg_install runners take --destdir.
"$BAZEL" --output_user_root="$CACHE" build --keep_going "${KOPTS[@]}" "${TARGETS[@]}" \
  || echo "[jm2-kleaf] WARNING: bazel build reported failures (continuing; per-target status below)"

FAILED=()
for t in "${TARGETS[@]}"; do
  tdir="$VSTAGE/$(echo "$t" | tr -c 'A-Za-z0-9' '_')"
  mkdir -p "$tdir"
  if ! "$BAZEL" --output_user_root="$CACHE" run "${KOPTS[@]}" "$t" -- --dist_dir "$tdir" >"$tdir/.run.log" 2>&1; then
    if ! "$BAZEL" --output_user_root="$CACHE" run "${KOPTS[@]}" "$t" -- --destdir "$tdir" >>"$tdir/.run.log" 2>&1; then
      FAILED+=("$t")
      tail -3 "$tdir/.run.log" | sed 's/^/[jm2-kleaf]     /'
    fi
  fi
done
if [ "${#FAILED[@]}" -gt 0 ]; then
  echo "[jm2-kleaf] WARNING: ${#FAILED[@]} vendor dist target(s) failed (their modules are absent; the coverage gate below catches any stock-needed loss):"
  printf '[jm2-kleaf]   %s\n' "${FAILED[@]}"
fi

echo "[jm2-kleaf] === 3/4 strip + merge vendor .ko into kernel dist ==="
# Remove everything a previous wrapper run merged, so a target that failed or
# vanished this run cannot leave a stale (old-kernel) module behind that the
# coverage gate would mistake for fresh.
if [ -f "$MERGE_MANIFEST" ]; then
  while read -r n; do [ -n "$n" ] && rm -f "$DIST/$n"; done < "$MERGE_MANIFEST"
  echo "[jm2-kleaf] cleaned $(wc -l < "$MERGE_MANIFEST") previously-merged .ko from dist"
fi
: > "$MERGE_MANIFEST.new"

# Cross-target same-basename collision check: identical content is fine (one
# copy merged); differing content is a real ambiguity — fail loudly.
declare -A KO_HASH KO_PATH
conflict=0
while IFS= read -r ko; do
  n="$(basename "$ko")"
  h="$(sha256sum "$ko" | cut -d' ' -f1)"
  if [ -n "${KO_HASH[$n]:-}" ] && [ "${KO_HASH[$n]}" != "$h" ]; then
    echo "[jm2-kleaf] ERROR: $n produced with DIFFERENT content by multiple targets:" >&2
    echo "[jm2-kleaf]   ${KO_PATH[$n]}" >&2
    echo "[jm2-kleaf]   $ko" >&2
    conflict=1
  else
    KO_HASH[$n]="$h"; KO_PATH[$n]="$ko"
  fi
done < <(find "$VSTAGE" -type f -name '*.ko' | sort)
[ "$conflict" -eq 0 ] || fail "same-basename vendor .ko with differing content — resolve before shipping"
[ "${#KO_HASH[@]}" -gt 0 ] || fail "no vendor .ko produced in $VSTAGE"

# The dist-target outputs are UNSTRIPPED (e.g. qca_cld3 ~540MB w/ DWARF); the OEM
# kernel dist modules are stripped. Strip to match (same as the kernel's
# INSTALL_MOD_STRIP=1: --strip-debug keeps symtab/modinfo/vermagic, so the module
# still loads + stays KMI-matched) before merging into the dist.
STRIPBINS=( "$KP"/prebuilts/clang/host/linux-x86/clang-r*/bin/llvm-strip )
STRIP="${STRIPBINS[0]:?llvm-strip not found in OEM clang prebuilts}"
for n in "${!KO_PATH[@]}"; do
  "$STRIP" --strip-debug "${KO_PATH[$n]}" -o "$DIST/$n" || fail "strip failed: ${KO_PATH[$n]}"
  echo "$n" >> "$MERGE_MANIFEST.new"
done
echo "[jm2-kleaf] merged ${#KO_PATH[@]} vendor .ko into dist"

# GKI system_dlkm modules: extract the ones the (collision-filtered)
# system_dlkm.modules.load names, flat into the dist, where the LOS kernel.mk
# system_dlkm split expects them. (They are the kernel's own GKI artifacts —
# shipped as-is, not re-stripped.)
gki_added=0
while read -r p; do
  [ -z "$p" ] && continue
  n="$(basename "$p")"
  if [ ! -f "$DIST/$n" ]; then
    src="$(find "$GKI_TMP" -name "$n" -type f | head -1)"
    if [ -n "$src" ]; then
      cp -f "$src" "$DIST/" && gki_added=$((gki_added+1)) && echo "$n" >> "$MERGE_MANIFEST.new"
    else
      echo "[jm2-kleaf] WARNING: $n in system_dlkm.modules.load but not in the staging archive" >&2
    fi
  fi
done < "$DIST/system_dlkm.modules.load"
mv "$MERGE_MANIFEST.new" "$MERGE_MANIFEST"
echo "[jm2-kleaf] added $gki_added GKI system_dlkm .ko from the staging archive"

echo "[jm2-kleaf] === 4/4 coverage + vermagic gate vs stock module lists ==="
# Every module the stock (booting) configuration loads OR stages must exist flat
# in the dist, EXCEPT the documented no-source gaps (known-source-gaps.txt):
# stock-loaded modules whose source is published nowhere; staging skips them via
# BOARD_KERNEL_MODULES_LOAD_ALLOW_MISSING. Any OTHER first-stage gap is a
# regression and fails the build here, loudly.
KNOWN_GAPS="$SCRIPT_DIR/known-source-gaps.txt"
is_known_gap() { [ -f "$KNOWN_GAPS" ] && grep -qxF "$1" <(grep -vE '^#|^$' "$KNOWN_GAPS"); }
report_gaps() {
  local list="$1" label="$2" hard="$3" miss=0 known=0 n
  if [ ! -f "$list" ]; then
    [ "$hard" = hard ] && { echo "[jm2-kleaf] ERROR: stock list missing: $list" >&2; return 1; }
    echo "[jm2-kleaf]   ($label: stock list not found, skipped)"; return 0
  fi
  while read -r p; do
    [ -z "$p" ] && continue
    n="$(basename "$p")"
    if [ ! -f "$DIST/$n" ]; then
      if is_known_gap "$n"; then known=$((known+1)); echo "[jm2-kleaf]   $label known-gap (tolerated): $n"
      else miss=$((miss+1)); echo "[jm2-kleaf]   $label MISSING: $n"; fi
    fi
  done < <(sort -u "$list")
  echo "[jm2-kleaf] $label: $miss missing + $known known-gaps (of $(sort -u "$list" | wc -l) unique stock entries)"
  if [ "$miss" -gt 0 ] && [ "$hard" = hard ]; then
    echo "[jm2-kleaf] ERROR: undocumented $label modules missing — fix or document before brunch" >&2
    return 1
  fi
  return 0
}
rc=0
# The staged first-stage set is the stock vendor_ramdisk DIRECTORY (BoardConfig
# mirrors the prebuilt wildcard), so gate on the directory contents too.
# (find -print -quit, NOT `ls | head`: under pipefail, head's early exit can
# SIGPIPE ls into a phantom failure.)
[ -n "$(find "$STOCK_MODULES_DIR/vendor_ramdisk" -maxdepth 1 -name '*.ko' -print -quit 2>/dev/null)" ] \
  || { echo "[jm2-kleaf] ERROR: no stock ramdisk .ko corpus" >&2; rc=1; }
find "$STOCK_MODULES_DIR/vendor_ramdisk" -maxdepth 1 -name '*.ko' 2>/dev/null > /tmp/.jm2_ramdisk_dir.txt
report_gaps /tmp/.jm2_ramdisk_dir.txt                                 "first-stage(staged-dir)" hard || rc=1
report_gaps "$STOCK_MODULES_DIR/vendor_ramdisk/modules.load"          "first-stage(load)"       hard || rc=1
report_gaps "$STOCK_MODULES_DIR/vendor_ramdisk/modules.load.recovery" "recovery"                hard || rc=1
report_gaps "$STOCK_MODULES_DIR/vendor_dlkm/modules.load"             "vendor_dlkm"             soft || true
report_gaps "$STOCK_MODULES_DIR/system_dlkm/modules.load"             "system_dlkm"             soft || true

# vermagic gate: every shipped .ko must match the freshly built kernel release —
# catches any stale module that slipped past the manifests. Reference = the
# vermagic of a module from THIS build's GKI staging archive (kbuild's
# kernel.release lives only inside bazel sandboxes; the archive is authoritative
# and already extracted in $GKI_TMP).
KREL_REF="$(find "$GKI_TMP" -name '*.ko' -type f -print -quit)"
KREL=""
[ -n "$KREL_REF" ] && KREL="$(/usr/sbin/modinfo -F vermagic "$KREL_REF" 2>/dev/null | awk '{print $1}')"
if [ -n "$KREL" ]; then
  bad=0
  while IFS= read -r ko; do
    vm="$(/usr/sbin/modinfo -F vermagic "$ko" 2>/dev/null | awk '{print $1}')"
    if [ -n "$vm" ] && [ "$vm" != "$KREL" ]; then
      echo "[jm2-kleaf]   VERMAGIC MISMATCH: $(basename "$ko") = $vm (kernel = $KREL)" >&2; bad=$((bad+1))
    fi
  done < <(find "$DIST" -maxdepth 1 -name '*.ko')
  if [ "$bad" -gt 0 ]; then echo "[jm2-kleaf] ERROR: $bad stale/mismatched .ko in dist" >&2; rc=1
  else echo "[jm2-kleaf] vermagic: all $(find "$DIST" -maxdepth 1 -name '*.ko' | wc -l) .ko match $KREL"; fi
else
  echo "[jm2-kleaf] ERROR: could not derive kernel release from the GKI archive — vermagic gate cannot run" >&2
  rc=1
fi

echo "[jm2-kleaf] dist now holds $(find "$DIST" -maxdepth 1 -name '*.ko' | wc -l) flat .ko"
[ "$rc" -eq 0 ] && echo "[jm2-kleaf] DONE." || echo "[jm2-kleaf] DONE WITH GATE FAILURES (see above)." >&2
exit "$rc"
