#!/bin/bash
# build-canoe-kleaf.sh — jm2 OEM-Kleaf build driver for canoe (OnePlus SM8850).
#
# Invoked by the LineageOS <-> OEM-Kleaf adapter in vendor/lineage's kernel.mk
# (TARGET_KERNEL_PLATFORM_BUILD_WRAPPER). The adapter runs us with cwd = the OEM
# repo root (TARGET_KERNEL_PLATFORM_ROOT, e.g. .../kernel-6.12), then copies the
# kernel dist into KERNEL_OUT.
#
# Why a wrapper (vs calling oplus_build_kernel.sh directly): the OEM kernel build
# (build_with_bazel.py) only builds soc-repo targets generated by define_canoe, so
# it EXCLUDES every //vendor/... DDK module set: the QC techpacks (display msm_drm,
# graphics msm_kgsl, camera, video/eva, audio, datarmnet/dataipa, securemsm, BT,
# dsp/fastrpc, mm-drivers, mmrm, synx, spu, NFC) plus WLAN (cnss2/qcacld — cnss2
# carries the OnePlus 15 byte-reversed-WLAN-MAC WiFi fix) and the oplus vendor
# modules not already merged by prepare_vendor. Without these the ROM has no
# display/audio/WiFi. We build ALL canoe_perf vendor dist targets against the SAME
# kernel_build (so KMI/CRCs match), plus extract the GKI system_dlkm modules the
# kernel build already produced into its staging archive, and merge everything
# into the kernel dist. Goal: full stock-module-set parity, fully source-built.
# See kernel/oneplus/sm8850-modules/KLEAF_WIREUP_PLAN.md.
#
# Usage: build-canoe-kleaf.sh <platform> <variant>   (e.g. canoe perf)
set -uo pipefail

# Detach stdin: the OEM kernel build runs `make oldconfig`, which prompts for any
# NEW Kconfig symbols. With EOF on stdin it auto-takes the defaults (exactly what
# the OEM's own clean build does); without it, a non-interactive caller (brunch,
# background) would block forever waiting for input.
exec </dev/null

PLATFORM="${1:?platform arg required (e.g. canoe)}"
VARIANT="${2:?variant arg required (e.g. perf)}"
TV="${PLATFORM}_${VARIANT}"

# We are run with cwd = OEM repo root; resolve everything from here.
ROOT="$(pwd)"
KP="$ROOT/kernel_platform"
DIST="$KP/out/msm-kernel-${PLATFORM}-${VARIANT}/dist"
CACHE="$ROOT/bazel-cache"
BAZEL="$KP/tools/bazel"

# Stock module-load lists (parity reference + coverage report). Overridable for
# other devices consuming this wrapper.
STOCK_MODULES_DIR="${STOCK_MODULES_DIR:-/run/media/jmulesa/lineage/android/lineage/device/oneplus/infiniti-kernel/modules}"

# grep is wrapped to ugrep in some shells and breaks the OEM scripts' parsing
# (same failure mode as `lunch`); neutralize it here. (reference_grep_ugrep_breaks_lunch)
unalias -a 2>/dev/null || true
unset -f grep egrep fgrep 2>/dev/null || true

fail() { echo "[jm2-kleaf] ERROR: $*" >&2; exit 1; }

echo "[jm2-kleaf] === 1/4 OEM kernel build ($TV) ==="
./kernel_platform/oplus/build/oplus_build_kernel.sh "$PLATFORM" "$VARIANT" || fail "OEM kernel build failed"
[ -f "$DIST/Image" ] || fail "no Image in $DIST after kernel build"

# Reuse the EXACT bazel config the kernel build recorded, so the vendor DDK modules
# build against the same ${TV} base kernel_build (cache hit + matching vermagic/CRCs).
# build_opts.txt stores opts with %workspace% tokens; expand them to $KP.
mapfile -t KOPTS < <(sed "s|%workspace%|$KP|g" "$DIST/build_opts.txt" | sort -u | grep -v '^$' || true)

VSTAGE="$ROOT/vendor_modules_dist"
rm -rf "$VSTAGE"; mkdir -p "$VSTAGE"

echo "[jm2-kleaf] === 2/4 vendor DDK module set ($TV) against the $TV kernel ==="
# bazel must run from the workspace root (kernel_platform), not the repo root
cd "$KP" || fail "cannot cd to workspace $KP"

# Enumerate every canoe_perf vendor dist target (same registry build_with_bazel
# queries, but across //vendor/... which it skips). Filter out the per-target
# internal helpers and qcacld's per-chipset duplicates of all_modules_dist.
mapfile -t TARGETS < <("$BAZEL" --output_user_root="$CACHE" query --keep_going \
    "filter(\"${TV}.*dist\", //vendor/...)" 2>/dev/null \
  | grep -E '^//' \
  | grep -vE '_dist_dist_manifest$|_dist_dist_tool$|_dist_internal$' \
  | grep -vE "qcacld-3\.0:${TV}_(kiwi|peach|wcn).*_modules_dist$" \
  | sort -u)
[ "${#TARGETS[@]}" -gt 0 ] || fail "vendor dist target enumeration returned nothing"
echo "[jm2-kleaf] ${#TARGETS[@]} vendor dist targets enumerated"

# One parallel build of everything first (much faster than serial runs), tolerant
# of individual target failures; then run each dist target (cache-hot) to copy its
# modules into the stage dir. copy_to_dist_dir runners take --dist_dir; pkg_install
# runners take --destdir — try both before declaring a target failed.
"$BAZEL" --output_user_root="$CACHE" build --keep_going "${KOPTS[@]}" "${TARGETS[@]}" \
  || echo "[jm2-kleaf] WARNING: bazel build reported failures (continuing; per-target status below)"

FAILED=()
for t in "${TARGETS[@]}"; do
  if ! "$BAZEL" --output_user_root="$CACHE" run "${KOPTS[@]}" "$t" -- --dist_dir "$VSTAGE" >/dev/null 2>&1; then
    if ! "$BAZEL" --output_user_root="$CACHE" run "${KOPTS[@]}" "$t" -- --destdir "$VSTAGE" >/dev/null 2>&1; then
      FAILED+=("$t")
    fi
  fi
done
if [ "${#FAILED[@]}" -gt 0 ]; then
  echo "[jm2-kleaf] WARNING: ${#FAILED[@]} vendor dist target(s) failed:"
  printf '[jm2-kleaf]   %s\n' "${FAILED[@]}"
fi

echo "[jm2-kleaf] === 3/4 strip + merge vendor .ko into kernel dist ==="
shopt -s nullglob
mapfile -t VENDOR_KOS < <(find "$VSTAGE" -type f -name '*.ko' | sort)
[ "${#VENDOR_KOS[@]}" -gt 0 ] || fail "no vendor .ko produced in $VSTAGE"
# The dist-target outputs are UNSTRIPPED (e.g. qca_cld3 ~540MB w/ DWARF); the OEM
# kernel dist modules are stripped. Strip to match (same as the kernel's
# INSTALL_MOD_STRIP=1: --strip-debug keeps symtab/modinfo/vermagic, so the module
# still loads + stays KMI-matched) before merging into the dist.
STRIPBINS=( "$KP"/prebuilts/clang/host/linux-x86/clang-r*/bin/llvm-strip )
STRIP="${STRIPBINS[0]:?llvm-strip not found in OEM clang prebuilts}"
for ko in "${VENDOR_KOS[@]}"; do
  "$STRIP" --strip-debug "$ko" -o "$DIST/$(basename "$ko")" || fail "strip failed: $ko"
done
echo "[jm2-kleaf] merged ${#VENDOR_KOS[@]} vendor .ko into dist"

# GKI system_dlkm modules: the kernel build produced them into the staging archive
# (not flat). Extract the ones the OEM's system_dlkm.modules.load names, flat into
# the dist, where the LOS kernel.mk system_dlkm split expects them. (They are the
# kernel's own GKI artifacts — already stripped/signed as the OEM ships them.)
GKI_TMP="$(mktemp -d)"
tar -xzf "$DIST/system_dlkm_staging_archive.tar.gz" -C "$GKI_TMP" || fail "system_dlkm staging archive extract failed"
gki_added=0
while read -r p; do
  [ -z "$p" ] && continue
  n="$(basename "$p")"
  if [ ! -f "$DIST/$n" ]; then
    src="$(find "$GKI_TMP" -name "$n" -type f | head -1)"
    [ -n "$src" ] && cp -f "$src" "$DIST/" && gki_added=$((gki_added+1))
  fi
done < "$DIST/system_dlkm.modules.load"
rm -rf "$GKI_TMP"
echo "[jm2-kleaf] added $gki_added GKI system_dlkm .ko from the staging archive"

echo "[jm2-kleaf] === 4/4 coverage report vs stock module-load lists ==="
# Every module the stock (booting) configuration loads must exist flat in the dist,
# EXCEPT the documented no-source gaps (known-source-gaps.txt next to this script):
# stock-loaded modules whose source is published nowhere; staging skips them via
# BOARD_KERNEL_MODULES_LOAD_ALLOW_MISSING. Any OTHER first-stage gap is a
# regression and fails the build here, loudly.
KNOWN_GAPS="$(dirname "$(readlink -f "$0")")/known-source-gaps.txt"
is_known_gap() { [ -f "$KNOWN_GAPS" ] && grep -qxF "$1" <(grep -vE '^#|^$' "$KNOWN_GAPS"); }
report_gaps() {
  local list="$1" label="$2" hard="$3" miss=0 known=0 n
  [ -f "$list" ] || { echo "[jm2-kleaf]   ($label: stock list not found, skipped)"; return 0; }
  while read -r p; do
    [ -z "$p" ] && continue
    n="$(basename "$p")"
    if [ ! -f "$DIST/$n" ]; then
      if is_known_gap "$n"; then known=$((known+1)); echo "[jm2-kleaf]   $label known-gap (tolerated): $n"
      else miss=$((miss+1)); echo "[jm2-kleaf]   $label MISSING: $n"; fi
    fi
  done < <(sort -u "$list")
  echo "[jm2-kleaf] $label: $miss missing + $known known-gaps (of $(sort -u "$list" | wc -l) unique stock entries)"
  if [ "$miss" -gt 0 ] && [ "$hard" = hard ]; then
    echo "[jm2-kleaf] ERROR: undocumented first-stage modules missing — fix or document before brunch" >&2
    return 1
  fi
  return 0
}
rc=0
report_gaps "$STOCK_MODULES_DIR/vendor_ramdisk/modules.load"          "first-stage"  hard || rc=1
report_gaps "$STOCK_MODULES_DIR/vendor_ramdisk/modules.load.recovery" "recovery"     hard || rc=1
report_gaps "$STOCK_MODULES_DIR/vendor_dlkm/modules.load"             "vendor_dlkm"  soft || true
report_gaps "$STOCK_MODULES_DIR/system_dlkm/modules.load"             "system_dlkm"  soft || true
echo "[jm2-kleaf] dist now holds $(find "$DIST" -maxdepth 1 -name '*.ko' | wc -l) flat .ko"
[ "$rc" -eq 0 ] && echo "[jm2-kleaf] DONE." || echo "[jm2-kleaf] DONE WITH FIRST-STAGE GAPS (see above)." >&2
exit "$rc"
